# Generated by Django 3.0 on 2025-06-18 23:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_deliveryorder_deliverypartner'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='deliverypartner',
            name='is_available',
        ),
        migrations.RemoveField(
            model_name='deliverypartner',
            name='user',
        ),
        migrations.AddField(
            model_name='deliverypartner',
            name='name',
            field=models.CharField(default='Partner', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='deliverypartner',
            name='password',
            field=models.CharField(default='temp_password', max_length=128),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='deliverypartner',
            name='phone',
            field=models.CharField(default='temp_password', max_length=15, unique=True),
            preserve_default=False,
        ),
    ]
